# -*- coding: utf-8 -*-
"""Copy of Derm_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXHWYg1Awwq2Zq0KJokiR1GcxgWTi-6S
"""

!pip -q install pandas matplotlib upsetplot

pip install pyranges

import pandas as pd
import gzip, os, re
import pyranges as pr

def open_maybe_gz(path):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path, "rt")

def parse_attrs(attr_str):
    # GFF3: key=value;key2=value2
    d = {}
    for part in attr_str.strip().split(";"):
        if "=" in part:
            k, v = part.split("=", 1)
            d[k.strip()] = v.strip()
    return d

def read_gff_intervals(path, feature_type="gene", keep_strand=False):
    """
    Returns a PyRanges object with columns:
      Chromosome, Start, End, (optional Strand)
    Note: GFF is 1-based inclusive. PyRanges uses 0-based half-open.
    """
    rows = []
    with open_maybe_gz(path) as f:
        for line in f:
            if not line or line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 9:
                continue
            seqid, source, ftype, start, end, score, strand, phase, attrs = parts
            if ftype != feature_type:
                continue

            start_i = int(start)
            end_i = int(end)

            # Convert 1-based inclusive -> 0-based half-open
            # [start_i, end_i] -> [start_i-1, end_i)
            rows.append({
                "Chromosome": seqid,
                "Start": start_i - 1,
                "End": end_i,
                "Strand": strand
            })

    df = pd.DataFrame(rows)
    if df.empty:
        # return empty PyRanges with correct columns
        if keep_strand:
            return pr.PyRanges(pd.DataFrame(columns=["Chromosome","Start","End","Strand"]))
        return pr.PyRanges(pd.DataFrame(columns=["Chromosome","Start","End"]))

    if not keep_strand:
        df = df[["Chromosome","Start","End"]]
    else:
        df = df[["Chromosome","Start","End","Strand"]]

    return pr.PyRanges(df)

import os
from google.colab import files

uploaded = files.upload()
paths = ["/content/" + f for f in uploaded.keys()]

#Set File Path
paths

import os

# Grab all GFF / GFF3 files already in /content
paths = [
    os.path.join("/content", f)
    for f in os.listdir("/content")
    if f.endswith((".gff", ".gff3", ".gff.gz", ".gff3.gz"))
]

paths

import pandas as pd
import gzip
import os
from collections import defaultdict
import numpy as np

def open_maybe_gz(path):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path, "rt")

def parse_gff_full(path):
    genes = {}
    transcripts = {}
    exons_by_tx = defaultdict(list)
    cds_by_tx = defaultdict(list)
    tx_to_gene = {}

    with open_maybe_gz(path) as f:
        for line in f:
            if not line or line.startswith("#"):
                continue
            parts = line.strip().split("\t")
            if len(parts) != 9:
                continue

            seqid, source, ftype, start, end, score, strand, phase, attrs = parts
            start = int(start)
            end = int(end)

            attr_dict = {}
            for item in attrs.split(";"):
                if "=" in item:
                    k,v = item.split("=",1)
                    attr_dict[k.strip()] = v.strip()

            if ftype == "gene":
                gid = attr_dict.get("ID")
                if gid:
                    genes[gid] = (start, end)

            if ftype in ("mRNA", "transcript"):
                tid = attr_dict.get("ID")
                parent = attr_dict.get("Parent")
                if tid:
                    transcripts[tid] = (start, end)
                    if parent:
                        tx_to_gene[tid] = parent

            if ftype == "exon":
                parent = attr_dict.get("Parent")
                if parent:
                    exons_by_tx[parent].append((start,end))

            if ftype == "CDS":
                parent = attr_dict.get("Parent")
                if parent:
                    cds_by_tx[parent].append((start,end))

    return genes, transcripts, exons_by_tx, cds_by_tx, tx_to_gene


def compute_stats(path):
    genes, transcripts, exons_by_tx, cds_by_tx, tx_to_gene = parse_gff_full(path)

    gene_lengths = [(e - s + 1) for s,e in genes.values()]
    tx_lengths = [(e - s + 1) for s,e in transcripts.values()]

    exon_counts = [len(exons_by_tx[tx]) for tx in transcripts]
    cds_lengths = []
    single_exon = 0

    for tx in transcripts:
        exons = exons_by_tx.get(tx, [])
        cds = cds_by_tx.get(tx, [])

        if len(exons) == 1:
            single_exon += 1

        cds_total = sum((e - s + 1) for s,e in cds)
        if cds_total > 0:
            cds_lengths.append(cds_total)

    return {
        "File": os.path.basename(path),
        "Total genes": len(genes),
        "Total transcripts": len(transcripts),
        "Mean gene length": np.mean(gene_lengths) if gene_lengths else 0,
        "Median gene length": np.median(gene_lengths) if gene_lengths else 0,
        "Mean exons per transcript": np.mean(exon_counts) if exon_counts else 0,
        "Median exons per transcript": np.median(exon_counts) if exon_counts else 0,
        "Mean CDS length": np.mean(cds_lengths) if cds_lengths else 0,
        "Median CDS length": np.median(cds_lengths) if cds_lengths else 0,
        "Single-exon transcripts (%)":
            (single_exon / len(transcripts) * 100) if transcripts else 0
    }


all_stats = [compute_stats(p) for p in paths]
stats_df = pd.DataFrame(all_stats)

stats_df

stats_df.to_excel("/content/full_annotation_stats.xlsx", index=False)

from google.colab import files
files.download("/content/full_annotation_stats.xlsx")

import pandas as pd
import pyranges as pr
import os

# Build a combined dataframe of all gene intervals
all_dfs = []

for p in paths:
    label = os.path.basename(p)
    gr = read_gff_intervals(p, feature_type="gene", keep_strand=False)
    df = gr.df.copy()
    df["File"] = label
    all_dfs.append(df)

combined_df = pd.concat(all_dfs, ignore_index=True)

# Recreate PyRanges from combined intervals (drop File for clustering)
combined_pr = pr.PyRanges(combined_df[["Chromosome","Start","End"]])

# Cluster overlapping regions
clusters = combined_pr.cluster()

cluster_df = clusters.df.copy()
cluster_df.head()

import pandas as pd
import pyranges as pr
import os
from collections import defaultdict

# Build per-file PyRanges for genes
ranges = {}
labels = []
for p in paths:
    lab = os.path.basename(p)
    labels.append(lab)
    ranges[lab] = read_gff_intervals(p, feature_type="gene", keep_strand=False)

# Combine all intervals and cluster
all_df = pd.concat([ranges[lab].df.assign(File=lab) for lab in labels], ignore_index=True)
combined_pr = pr.PyRanges(all_df[["Chromosome","Start","End"]])
clusters = combined_pr.cluster()

# Map: cluster_id -> set(files that hit it)
cluster_to_files = defaultdict(set)

# For each file, find which clusters overlap its genes (ONE overlap per file)
for lab in labels:
    if len(ranges[lab]) == 0:
        continue
    ov = clusters.overlap(ranges[lab])  # fast
    hit = set(ov.df["Cluster"].astype(int).tolist())
    for cid in hit:
        cluster_to_files[cid].add(lab)

# Build memberships list (one per cluster)
all_cluster_ids = clusters.df["Cluster"].astype(int).unique()
memberships = [tuple(sorted(cluster_to_files.get(cid, set()))) for cid in all_cluster_ids]

# Optional: drop empty memberships (clusters that somehow hit nothing)
memberships = [m for m in memberships if len(m) > 0]

len(memberships), memberships[:5]

from collections import Counter
import pandas as pd
from upsetplot import from_memberships, UpSet
import matplotlib.pyplot as plt

# memberships = list of tuples like ('fileA.gff', 'fileB.gff3')
counts = Counter(memberships)

# Build UpSet data from unique membership keys and their counts
unique_memberships = list(counts.keys())
weights = list(counts.values())

data = from_memberships(unique_memberships, data=weights)  # Series with unique groups

plt.figure(figsize=(12,6))
UpSet(data, show_counts=True, sort_by="cardinality").plot()
plt.suptitle("Unique vs Shared Gene Loci (Coordinate Overlap)")
plt.tight_layout()
plt.show()

# Optional: also create a table you can export
overlap_counts = pd.DataFrame({
    "membership": [" & ".join(m) for m in unique_memberships],
    "count": weights
}).sort_values("count", ascending=False)

overlap_counts.head(10)

overlap_counts.to_csv("/content/coordinate_overlap_membership_counts.csv", index=False)
overlap_counts.to_excel("/content/coordinate_overlap_membership_counts.xlsx", index=False)

from google.colab import files
files.download("/content/coordinate_overlap_membership_counts.csv")
files.download("/content/coordinate_overlap_membership_counts.xlsx")

from collections import Counter
import pandas as pd
from upsetplot import from_memberships, UpSet
import matplotlib.pyplot as plt

# Aggregate memberships
counts = Counter(memberships)
unique_memberships = list(counts.keys())
weights = list(counts.values())

data = from_memberships(unique_memberships, data=weights)

# Make BIG readable figure
fig = plt.figure(figsize=(16,10))  # much larger

up = UpSet(
    data,
    show_counts=True,
    sort_by="cardinality"
)

up.plot(fig=fig)
fig = plt.figure(figsize=(20,12))

plt.suptitle(
    "Unique vs Shared Gene Loci (Coordinate Overlap)",
    fontsize=18
)

plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(20,12))

!pip install venn

from matplotlib_venn import venn2, venn3
import matplotlib.pyplot as plt

labels = list(set([lab for combo in memberships for lab in combo]))

# Build sets of cluster IDs per file
file_sets = {}
for lab in labels:
    file_sets[lab] = set(
        i for i,m in enumerate(memberships) if lab in m
    )

plt.figure(figsize=(10,10))

if len(labels) == 2:
    venn = venn2(
        [file_sets[labels[0]], file_sets[labels[1]]],
        set_labels=labels
    )
elif len(labels) == 3:
    venn = venn3(
        [file_sets[labels[0]], file_sets[labels[1]], file_sets[labels[2]]],
        set_labels=labels
    )

# Custom colors
colors = ["#4C72B0", "#DD8452", "#55A868"]
for i, patch in enumerate(venn.patches):
    if patch:
        patch.set_color(colors[i % len(colors)])
        patch.set_alpha(0.6)

plt.title("Shared vs Unique Gene Loci", fontsize=18)
plt.show()

from collections import Counter
import matplotlib.pyplot as plt
from upsetplot import from_memberships, UpSet
import re

# ---- You should already have `memberships` from your coordinate overlap code ----
# memberships = [("fileA.gff",), ("fileB.gff",), ("fileA.gff","fileB.gff"), ...]

# ---------- Helper: turn filename into organism label ----------
def organism_from_filename(fn: str) -> str:
    # strip extensions
    s = re.sub(r"\.(gff3?|gff3?\.gz)$", "", fn)
    # you can customize this: e.g. keep just genus_species
    return s

# Aggregate membership combos -> counts
counts = Counter(memberships)
unique_memberships = list(counts.keys())
weights = list(counts.values())

data = from_memberships(unique_memberships, data=weights)

# Extract all set names from the membership tuples
set_names = sorted({name for combo in unique_memberships for name in combo})

# Assign a distinct color to each organism (matplotlib tab10)
cmap = plt.get_cmap("tab10")
color_map = {name: cmap(i % 10) for i, name in enumerate(set_names)}

# ---- Make the plot BIG + readable ----
fig = plt.figure(figsize=(20, 12), dpi=160)

up = UpSet(
    data,
    show_counts=True,
    sort_by="cardinality",
    sort_categories_by="cardinality",
)
up.plot(fig=fig)

# Title
fig.suptitle("Unique vs Shared Loci (Coordinate Overlap)", fontsize=22, y=1.02)

# ---- Color the set-size bars + y tick labels ----
# UpSet creates multiple axes; the set-size axis is usually named 'set_size'
ax_setsize = up.ax_dict.get("set_size", None)
ax_matrix  = up.ax_dict.get("matrix", None)
ax_intsize = up.ax_dict.get("intersections", None)

# Color the horizontal set-size bars
if ax_setsize is not None:
    # bars correspond to set_names in the plotted order (upsetplot uses internal ordering)
    # We'll infer the tick labels order and color accordingly.
    ticklabels = [t.get_text() for t in ax_setsize.get_yticklabels()]
    for bar, lab in zip(ax_setsize.patches, ticklabels):
        if lab in color_map:
            bar.set_facecolor(color_map[lab])
            bar.set_edgecolor("black")
            bar.set_linewidth(0.5)

    # Color the y tick labels
    for t in ax_setsize.get_yticklabels():
        lab = t.get_text()
        if lab in color_map:
            t.set_color(color_map[lab])
            t.set_fontsize(12)

# Make intersection-size text larger
if ax_intsize is not None:
    ax_intsize.tick_params(axis="both", labelsize=12)

# Make matrix labels larger + readable
if ax_matrix is not None:
    ax_matrix.tick_params(axis="both", labelsize=12)

plt.tight_layout()

# Save a high-res copy
out_png = "/content/upset_colored_big.png"
plt.savefig(out_png, bbox_inches="tight")
plt.show()

print("Saved:", out_png)

!pip install biopython

from Bio import SeqIO

input_file = "your_file.gbff"
output_file = "converted.gff3"

with open(output_file, "w") as out:
    out.write("##gff-version 3\n")
    for record in SeqIO.parse(input_file, "genbank"):
        for feature in record.features:
            if feature.type in ["gene", "CDS", "mRNA", "exon"]:
                start = int(feature.location.start) + 1
                end = int(feature.location.end)
                strand = "+" if feature.location.strand == 1 else "-"

                attrs = []
                if "locus_tag" in feature.qualifiers:
                    attrs.append("ID=" + feature.qualifiers["locus_tag"][0])
                if "gene" in feature.qualifiers:
                    attrs.append("Name=" + feature.qualifiers["gene"][0])

                attr_str = ";".join(attrs)

                out.write(
                    f"{record.id}\tGenBank\t{feature.type}\t"
                    f"{start}\t{end}\t.\t{strand}\t.\t{attr_str}\n"
                )



import os
from google.colab import files

uploaded = files.upload()

from Bio import SeqIO

input_file = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"
output_file = "Dermacentor_reticulatus_converted.gff3"

with open(output_file, "w") as out:
    out.write("##gff-version 3\n")
    for record in SeqIO.parse(input_file, "genbank"):
        for feature in record.features:
            if feature.type in ["gene", "CDS", "mRNA", "exon"]:
                start = int(feature.location.start) + 1
                end = int(feature.location.end)
                strand = "+" if feature.location.strand == 1 else "-"

                attrs = []
                if "locus_tag" in feature.qualifiers:
                    attrs.append("ID=" + feature.qualifiers["locus_tag"][0])
                if "gene" in feature.qualifiers:
                    attrs.append("Name=" + feature.qualifiers["gene"][0])

                attr_str = ";".join(attrs)

                out.write(
                    f"{record.id}\tGenBank\t{feature.type}\t"
                    f"{start}\t{end}\t.\t{strand}\t.\t{attr_str}\n"
                )

import os

paths = sorted([
    os.path.join("/content", f)
    for f in os.listdir("/content")
    if f.endswith((".gff", ".gff3", ".gff.gz", ".gff3.gz"))
])

paths

import pandas as pd
import gzip, os
from collections import defaultdict
import numpy as np

def open_maybe_gz(path):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path, "rt")

def parse_gff_full(path):
    genes = {}
    transcripts = {}
    exons_by_tx = defaultdict(list)
    cds_by_tx = defaultdict(list)

    with open_maybe_gz(path) as f:
        for line in f:
            if not line or line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 9:
                continue

            seqid, source, ftype, start, end, score, strand, phase, attrs = parts
            start = int(start)
            end = int(end)

            # Parse attributes (GFF3 style key=value)
            attr = {}
            for item in attrs.split(";"):
                if "=" in item:
                    k, v = item.split("=", 1)
                    attr[k.strip()] = v.strip()

            if ftype == "gene":
                gid = attr.get("ID")
                if gid:
                    genes[gid] = (start, end)

            elif ftype in ("mRNA", "transcript"):
                tid = attr.get("ID")
                if tid:
                    transcripts[tid] = (start, end)

            elif ftype == "exon":
                parent = attr.get("Parent")
                if parent:
                    # Parent may contain multiple IDs separated by commas
                    for p in parent.split(","):
                        exons_by_tx[p].append((start, end))

            elif ftype == "CDS":
                parent = attr.get("Parent")
                if parent:
                    for p in parent.split(","):
                        cds_by_tx[p].append((start, end))

    return genes, transcripts, exons_by_tx, cds_by_tx


def compute_stats(path):
    genes, transcripts, exons_by_tx, cds_by_tx = parse_gff_full(path)

    gene_lengths = [(e - s + 1) for s, e in genes.values()]

    # exon counts per transcript (only for transcripts we saw)
    exon_counts = [len(exons_by_tx.get(t, [])) for t in transcripts.keys()]

    # CDS length per transcript = sum of CDS segments for that transcript
    cds_lengths = []
    for t in transcripts.keys():
        cds = cds_by_tx.get(t, [])
        cds_total = sum((e - s + 1) for s, e in cds)
        if cds_total > 0:
            cds_lengths.append(cds_total)

    # single-exon transcripts (%)
    single_exon = sum(1 for c in exon_counts if c == 1)
    tx_total = len(transcripts)

    return {
        "File": os.path.basename(path),
        "Total genes": len(genes),
        "Total transcripts": tx_total,
        "Mean gene length": float(np.mean(gene_lengths)) if gene_lengths else 0.0,
        "Median gene length": float(np.median(gene_lengths)) if gene_lengths else 0.0,
        "Mean exons per transcript": float(np.mean(exon_counts)) if exon_counts else 0.0,
        "Median exons per transcript": float(np.median(exon_counts)) if exon_counts else 0.0,
        "Mean CDS length": float(np.mean(cds_lengths)) if cds_lengths else 0.0,
        "Median CDS length": float(np.median(cds_lengths)) if cds_lengths else 0.0,
        "Single-exon transcripts (%)": float(single_exon / tx_total * 100) if tx_total else 0.0,
    }

stats_df = pd.DataFrame([compute_stats(p) for p in paths]).sort_values("File")
stats_df

import matplotlib.pyplot as plt
import numpy as np

# Expect stats_df exists from earlier and includes the columns below
cols_needed = [
    "File",
    "Total genes",
    "Total transcripts",
    "Mean gene length",
    "Median gene length",
    "Mean exons per transcript",
    "Median exons per transcript",
    "Mean CDS length",
    "Median CDS length",
    "Single-exon transcripts (%)",
]
missing = [c for c in cols_needed if c not in stats_df.columns]
if missing:
    raise ValueError(f"stats_df missing columns: {missing}")

df = stats_df.copy().sort_values("File").reset_index(drop=True)

files = df["File"].tolist()
x = np.arange(len(files))
w = 0.38  # bar width

# Figure
fig = plt.figure(figsize=(18, 14), dpi=160)
gs = fig.add_gridspec(3, 2, height_ratios=[1.1, 1.1, 0.9], hspace=0.35, wspace=0.25)

ax1 = fig.add_subplot(gs[0, 0])  # counts
ax2 = fig.add_subplot(gs[0, 1])  # gene len
ax3 = fig.add_subplot(gs[1, 0])  # exons per tx
ax4 = fig.add_subplot(gs[1, 1])  # cds len
ax5 = fig.add_subplot(gs[2, :])  # single-exon %

# -------- Panel A: Total genes / transcripts --------
ax1.bar(x - w/2, df["Total genes"], width=w, label="Total genes")
ax1.bar(x + w/2, df["Total transcripts"], width=w, label="Total transcripts")
ax1.set_title("Counts")
ax1.set_ylabel("Count")
ax1.set_xticks(x)
ax1.set_xticklabels(files, rotation=45, ha="right", fontsize=9)
ax1.legend()

# -------- Panel B: Gene length (mean/median) --------
ax2.bar(x - w/2, df["Mean gene length"], width=w, label="Mean gene length")
ax2.bar(x + w/2, df["Median gene length"], width=w, label="Median gene length")
ax2.set_title("Gene length (bp)")
ax2.set_ylabel("bp")
ax2.set_xticks(x)
ax2.set_xticklabels(files, rotation=45, ha="right", fontsize=9)
ax2.legend()

# -------- Panel C: Exons per transcript --------
ax3.bar(x - w/2, df["Mean exons per transcript"], width=w, label="Mean exons/tx")
ax3.bar(x + w/2, df["Median exons per transcript"], width=w, label="Median exons/tx")
ax3.set_title("Exons per transcript")
ax3.set_ylabel("Count")
ax3.set_xticks(x)
ax3.set_xticklabels(files, rotation=45, ha="right", fontsize=9)
ax3.legend()

# -------- Panel D: CDS length (mean/median) --------
ax4.bar(x - w/2, df["Mean CDS length"], width=w, label="Mean CDS length")
ax4.bar(x + w/2, df["Median CDS length"], width=w, label="Median CDS length")
ax4.set_title("CDS length per transcript (bp)")
ax4.set_ylabel("bp")
ax4.set_xticks(x)
ax4.set_xticklabels(files, rotation=45, ha="right", fontsize=9)
ax4.legend()

# -------- Panel E: Single-exon transcript % --------
ax5.bar(x, df["Single-exon transcripts (%)"])
ax5.set_title("Single-exon transcripts (%)")
ax5.set_ylabel("%")
ax5.set_xticks(x)
ax5.set_xticklabels(files, rotation=45, ha="right", fontsize=9)

fig.suptitle("Annotation comparison across GFF/GFF3 files", fontsize=18, y=1.01)
plt.tight_layout()

out = "/content/annotation_stats_comparison.png"
plt.savefig(out, bbox_inches="tight")
plt.show()

print("Saved:", out)

import os, gzip

input_file = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"
print("GBFF size (bytes):", os.path.getsize(input_file))

# show first ~30 lines
!head -n 30 "$input_file"

!pip -q install biopython bcbio-gff

from BCBio import GFF
from Bio import SeqIO
import os

input_file = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"
out_file = "/content/Dermacentor_reticulatus.converted.gff3"

# Parse GenBank records (GBFF can contain multiple records)
records = list(SeqIO.parse(input_file, "genbank"))
print("Records parsed:", len(records))

with open(out_file, "w") as out_handle:
    GFF.write(records, out_handle)

print("Wrote:", out_file)
print("GFF3 size (bytes):", os.path.getsize(out_file))

import os

paths = sorted([
    os.path.join("/content", f)
    for f in os.listdir("/content")
    if f.endswith((".gff", ".gff3", ".gff.gz", ".gff3.gz"))
])

paths

import pandas as pd
import gzip
import numpy as np
from collections import defaultdict

def open_maybe_gz(path):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path, "rt")

def parse_gff_full(path):
    genes = {}
    transcripts = {}
    exons_by_tx = defaultdict(list)
    cds_by_tx = defaultdict(list)

    with open_maybe_gz(path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.strip().split("\t")
            if len(parts) != 9:
                continue

            chrom, source, ftype, start, end, score, strand, phase, attrs = parts
            start = int(start)
            end = int(end)

            attr_dict = {}
            for item in attrs.split(";"):
                if "=" in item:
                    k, v = item.split("=", 1)
                    attr_dict[k.strip()] = v.strip()

            if ftype == "gene":
                gid = attr_dict.get("ID")
                if gid:
                    genes[gid] = (start, end)

            elif ftype in ("mRNA", "transcript"):
                tid = attr_dict.get("ID")
                if tid:
                    transcripts[tid] = (start, end)

            elif ftype == "exon":
                parent = attr_dict.get("Parent")
                if parent:
                    for p in parent.split(","):
                        exons_by_tx[p].append((start, end))

            elif ftype == "CDS":
                parent = attr_dict.get("Parent")
                if parent:
                    for p in parent.split(","):
                        cds_by_tx[p].append((start, end))

    return genes, transcripts, exons_by_tx, cds_by_tx


def compute_stats(path):
    genes, transcripts, exons_by_tx, cds_by_tx = parse_gff_full(path)

    gene_lengths = [(e - s + 1) for s, e in genes.values()]
    exon_counts = [len(exons_by_tx.get(t, [])) for t in transcripts]
    cds_lengths = [
        sum((e - s + 1) for s, e in cds_by_tx.get(t, []))
        for t in transcripts
        if cds_by_tx.get(t)
    ]

    single_exon = sum(1 for c in exon_counts if c == 1)
    tx_total = len(transcripts)

    return {
        "File": os.path.basename(path),
        "Total genes": len(genes),
        "Total transcripts": tx_total,
        "Mean gene length": np.mean(gene_lengths) if gene_lengths else 0,
        "Median gene length": np.median(gene_lengths) if gene_lengths else 0,
        "Mean exons per transcript": np.mean(exon_counts) if exon_counts else 0,
        "Median exons per transcript": np.median(exon_counts) if exon_counts else 0,
        "Mean CDS length": np.mean(cds_lengths) if cds_lengths else 0,
        "Median CDS length": np.median(cds_lengths) if cds_lengths else 0,
        "Single-exon transcripts (%)": (single_exon / tx_total * 100) if tx_total else 0,
    }

stats_df = pd.DataFrame([compute_stats(p) for p in paths]).sort_values("File")
stats_df

import matplotlib.pyplot as plt
import numpy as np

df = stats_df.sort_values("File").reset_index(drop=True)
files = df["File"].tolist()
x = np.arange(len(files))
w = 0.35

fig = plt.figure(figsize=(18,14), dpi=160)
gs = fig.add_gridspec(3,2, hspace=0.35, wspace=0.25)

ax1 = fig.add_subplot(gs[0,0])
ax2 = fig.add_subplot(gs[0,1])
ax3 = fig.add_subplot(gs[1,0])
ax4 = fig.add_subplot(gs[1,1])
ax5 = fig.add_subplot(gs[2,:])

# Counts
ax1.bar(x-w/2, df["Total genes"], width=w, label="Genes")
ax1.bar(x+w/2, df["Total transcripts"], width=w, label="Transcripts")
ax1.set_title("Total Genes & Transcripts")
ax1.legend()

# Gene length
ax2.bar(x-w/2, df["Mean gene length"], width=w, label="Mean")
ax2.bar(x+w/2, df["Median gene length"], width=w, label="Median")
ax2.set_title("Gene Length (bp)")
ax2.legend()

# Exons per transcript
ax3.bar(x-w/2, df["Mean exons per transcript"], width=w, label="Mean")
ax3.bar(x+w/2, df["Median exons per transcript"], width=w, label="Median")
ax3.set_title("Exons per Transcript")
ax3.legend()

# CDS length
ax4.bar(x-w/2, df["Mean CDS length"], width=w, label="Mean")
ax4.bar(x+w/2, df["Median CDS length"], width=w, label="Median")
ax4.set_title("CDS Length (bp)")
ax4.legend()

# Single exon %
ax5.bar(x, df["Single-exon transcripts (%)"])
ax5.set_title("Single-Exon Transcripts (%)")

for ax in [ax1,ax2,ax3,ax4,ax5]:
    ax.set_xticks(x)
    ax.set_xticklabels(files, rotation=45, ha="right", fontsize=9)

fig.suptitle("Annotation Structural Comparison", fontsize=20)
plt.tight_layout()

plt.savefig("/content/annotation_stats_comparison.png", bbox_inches="tight")
plt.show()

import gzip
from collections import Counter

path = "/content/Dermacentor_reticulatus.converted.gff3"

def open_maybe_gz(p):
    return gzip.open(p, "rt") if p.endswith(".gz") else open(p, "rt")

ct = Counter()
n = 0
with open_maybe_gz(path) as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.rstrip("\n").split("\t")
        if len(parts) != 9:
            continue
        ct[parts[2]] += 1
        n += 1

print("Total feature lines:", n)
print("Top 30 feature types:")
for k,v in ct.most_common(30):
    print(f"{k}\t{v}")

path = "/content/Dermacentor_reticulatus.converted.gff3"
with open(path) as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.rstrip("\n").split("\t")
        if len(parts) == 9:
            print("Example feature line:\n", line[:300])
            print("\nAttributes field:\n", parts[8][:300])
            break

from Bio import SeqIO
import numpy as np
from collections import defaultdict
import os

gbff_path = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"

genes = {}
transcripts = {}
exons_by_tx = defaultdict(list)
cds_by_tx = defaultdict(list)

for record in SeqIO.parse(gbff_path, "genbank"):
    for feature in record.features:

        if feature.type == "gene":
            gene_id = feature.qualifiers.get("locus_tag",
                       feature.qualifiers.get("gene", ["unknown"]))[0]
            genes[gene_id] = len(feature.location)

        elif feature.type == "CDS":
            tid = feature.qualifiers.get("protein_id",
                  feature.qualifiers.get("locus_tag", ["unknown"]))[0]

            cds_by_tx[tid].append(len(feature.location))
            transcripts[tid] = True

        elif feature.type == "exon":
            tid = feature.qualifiers.get("transcript_id", ["unknown"])[0]
            exons_by_tx[tid].append(len(feature.location))

gene_lengths = list(genes.values())
cds_lengths = [sum(v) for v in cds_by_tx.values()]
exon_counts = [len(exons_by_tx.get(t, [])) for t in transcripts]

stats = {
    "File": os.path.basename(gbff_path),
    "Total genes": len(genes),
    "Total transcripts": len(transcripts),
    "Mean gene length": np.mean(gene_lengths) if gene_lengths else 0,
    "Median gene length": np.median(gene_lengths) if gene_lengths else 0,
    "Mean exons per transcript": np.mean(exon_counts) if exon_counts else 0,
    "Median exons per transcript": np.median(exon_counts) if exon_counts else 0,
    "Mean CDS length": np.mean(cds_lengths) if cds_lengths else 0,
    "Median CDS length": np.median(cds_lengths) if cds_lengths else 0,
    "Single-exon transcripts (%)":
        (sum(1 for c in exon_counts if c == 1) / len(exon_counts) * 100)
        if exon_counts else 0
}

stats

gbff_path = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"
!grep -n "^FEATURES" -m 3 "$gbff_path" || echo "No FEATURES section"
!grep -n "^\s\{5\}gene\s" -m 5 "$gbff_path" || echo "No gene features"
!grep -n "^\s\{5\}CDS\s" -m 5 "$gbff_path" || echo "No CDS features"

gbff_path = "/content/drive/MyDrive/Dermacentor_reticulatus.gbff"

from collections import Counter
from Bio import SeqIO

ct = Counter()
n_records = 0
n_features = 0

for rec in SeqIO.parse(gbff_path, "genbank"):
    n_records += 1
    for feat in rec.features:
        n_features += 1
        ct[feat.type] += 1

print("Records:", n_records)
print("Total features:", n_features)
print("\nTop feature types:")
for k,v in ct.most_common(30):
    print(f"{k}\t{v}")

print("\nHas gene?", "gene" in ct, "count:", ct.get("gene", 0))
print("Has CDS?", "CDS" in ct, "count:", ct.get("CDS", 0))
print("Has mRNA?", "mRNA" in ct, "count:", ct.get("mRNA", 0))